### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/gfroerli-api#24]
According to the [schema.rb](https://github.com/coredump-ch/water-sensor-api/blob/master/db/schema.rb) many fields are still nullable. Can we make the following fields non-null?

- sensors.device_name (disallow blank)
- sensors.caption (allow blank)
- sponsors.name (disallow blank)
- sponsors.active (maybe default to 't' on create)
- measurements.temperature
- measurements.sensor_id

**Comment by schmijos** [comment]
I'd disallow blank for sensor captions

**Comment by dbrgn** [comment]
Fine with me!

(There's no semantic difference, but there's a difference when handling the two variants in programming languages with non-nullable types.)
