### ISSUE TITLE
Smaller responses: Better data types

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/gfroerli-api#42]
This is a follow-up of #41.

Even if we could filter the keys, if we return a lot of measurements every entry looks like this:

```json
    {
        "temperature": "11.6125068664551",
        "created_at": "2018-03-10T16:35:00.980Z"
    },
    {
        "temperature": "11.6125068664551",
        "created_at": "2018-03-10T16:45:06.590Z"
    },
    ...
```

We could save a lot of traffic by using floats instead of strings for the temperature and unix timestamps instead of strings for the date. What do you think, @schmijos?

Also, renaming `temperature` to `temp` probably wouldn't hurt.

**Comment by rnestler** [comment]
> We could save a lot of traffic by using floats instead of strings for the temperature and unix timestamps instead of strings for the date.

I agree that we should use floats, but it won't reduce size much, would it? We'd just get rid of the `"`.

**Comment by dbrgn** [comment]
Ah stupid me, I was thinking of binary encoding :) Still, it would be simpler for the applications if the values are sent as floats.

**Comment by dbrgn** [comment]
Duplicate of #27 and #54.
